spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: 12345678
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
    hu:
      jandzsogyorgy: debug

    root: info

server:
  port: 8888

jwt:
  secret: your_very_long_and_secure_secret_key_here
  expiration: 3600000  # 1 hour in milliseconds
