server:
  port: 8888



cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600


# Should me masked for PROD
proxmox:
  host: 10.3.2.11
  port: 8006
  username: root
  password: 12345678


logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
    hu:
      jandzsogyorgy: debug

    root: info

    it:
      corsinvest:
        proxmoxve: debug
