logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug
    hu:
      jandzsogyorgy: debug

    root: info

    it:
      corsinvest:
        proxmoxve: debug


server:
  port: 8888


# Should me masked for PROD
proxmox:
  host: 10.3.2.11
  port: 8006
  username: root
  password: 12345678


